# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-03 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('votes', models.IntegerField()),
                ('image', models.FileField(upload_to=b'')),
            ],
        ),
    ]
