# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-03 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
